import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import App from "@/app";
import { Toaster } from "@/components/ui/sonner"
import Layout from "@/components/layout";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Avax",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <App>
          <Layout>
            {children}
            <Toaster className="bg-black" />
          </Layout>
        </App>
      </body>
    </html>
  );
}
