import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import App from "@/app";
import { Toaster } from "@/components/ui/sonner"



export const metadata: Metadata = {
  title: "Avax",
  description: "Generated by create next app",
};

export default function RootLayout({ children,}: Readonly<{ children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body>
          <App>
            {children}
            <Toaster />
          </App>
      </body>
    </html>
  );
}
